-- ============================================================
-- Migration: daily_reports table + n8n CSV storage
-- Purpose: Store CSV files generated by n8n workflow runs
-- ============================================================

-- 1. Ensure the daily_reports table exists with all needed columns
CREATE TABLE IF NOT EXISTS daily_reports (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_date   DATE NOT NULL DEFAULT CURRENT_DATE,
  report_name   TEXT,
  file_url      TEXT,
  file_path     TEXT,          -- storage path inside the bucket
  csv_content   TEXT,          -- optional: raw CSV inline (for small reports)
  row_count     INTEGER DEFAULT 0,
  file_size_bytes BIGINT DEFAULT 0,
  trg_percentage NUMERIC(5,2) DEFAULT 0,
  trs_percentage NUMERIC(5,2) DEFAULT 0,
  total_losses   INTEGER DEFAULT 0,
  scope          TEXT DEFAULT 'all',      -- 'all' | 'in_progress' | 'completed'
  source         TEXT DEFAULT 'n8n',      -- who generated it
  workflow_run_id TEXT,                    -- n8n execution ID for dedup
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Prevent duplicate n8n runs from inserting the same report twice
CREATE UNIQUE INDEX IF NOT EXISTS daily_reports_workflow_run_id_idx
  ON daily_reports (workflow_run_id)
  WHERE workflow_run_id IS NOT NULL;

-- 3. Index for chronological listing
CREATE INDEX IF NOT EXISTS daily_reports_report_date_idx
  ON daily_reports (report_date DESC);

-- 4. RLS — enable row-level security
ALTER TABLE daily_reports ENABLE ROW LEVEL SECURITY;

-- Admins & supervisors can read all reports
DROP POLICY IF EXISTS "reports_select" ON daily_reports;
CREATE POLICY "reports_select" ON daily_reports
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'supervisor')
    )
  );

-- Only service-role (used by n8n / edge functions) can insert
DROP POLICY IF EXISTS "reports_insert_service" ON daily_reports;
CREATE POLICY "reports_insert_service" ON daily_reports
  FOR INSERT
  TO authenticated
  WITH CHECK (true);   -- rely on anon/service key at the API layer

-- Service role can update (e.g. attach file_url after upload)
DROP POLICY IF EXISTS "reports_update_service" ON daily_reports;
CREATE POLICY "reports_update_service" ON daily_reports
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- 5. Storage bucket for n8n CSV files
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'n8n-reports',
  'n8n-reports',
  true,
  52428800,   -- 50 MB
  ARRAY['text/csv', 'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/json', 'application/octet-stream']
)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to read files
DROP POLICY IF EXISTS "n8n_reports_read" ON storage.objects;
CREATE POLICY "n8n_reports_read" ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id = 'n8n-reports');

-- Allow service role / anon with service key to upload
DROP POLICY IF EXISTS "n8n_reports_insert" ON storage.objects;
CREATE POLICY "n8n_reports_insert" ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'n8n-reports');
